<map version="0.9.0">
<!-- To view this file, download free mind mapping software FreeMind from http://freemind.sourceforge.net -->
<node CREATED="1255032351279" ID="ID_538065592" MODIFIED="1255032361324" TEXT="Optimal generators">
<node CREATED="1255032361577" ID="ID_383483898" MODIFIED="1255033115673" POSITION="right" TEXT="Definition: An ordered sequence of generators G is optimal if and only if any other sequence of generators G&apos; satisfies M(G(i)) &gt;= M(G&apos;(i)) for every i."/>
<node CREATED="1255032896856" ID="ID_186300806" MODIFIED="1255032923898" POSITION="right" TEXT="Definition:  A sequence of generators is said to be an ordered sequence if M(G(i)) &gt;= M(G(j)) for j &gt;= i."/>
<node CREATED="1255032506627" ID="ID_319070318" MODIFIED="1255033110166" POSITION="right" TEXT="Definition:  A segregation of X of size N is a pair (G,X&apos;) consisting of an ordered sequence of N generators, G, of some subset of X, and a subset of operators X&apos; which commute with the generators in G.  A given segregation of X of size N, (G,X&apos;) is said to be optimal if for every other segregation of X of size N, (G&apos;,X&apos;&apos;), we have that M(G(i)) &gt;= M(G&apos;(i)) for every i."/>
<node CREATED="1255033155361" ID="ID_622313009" MODIFIED="1255033225773" POSITION="right" TEXT="Definition:  A &quot;split&quot; of an ordered sequence of generators is a segregation (G&apos;,X&apos;) such that G&apos; is some subsequence of G starting from the left and X&apos; is the subset of operators generated by G which commute with every generator in G."/>
<node CREATED="1255032470948" ID="ID_647555103" MODIFIED="1255032887564" POSITION="right" TEXT="Theorem: An ordered sequence of generators is optimal if and only if every split is an optimal segregation.">
<node CREATED="1255033129386" ID="ID_694618866" MODIFIED="1255033310363" TEXT="=&gt; If a split is not an optimal segregation, then this implies that we can construct a &quot;better&quot; set of generators than G."/>
<node CREATED="1255033313375" ID="ID_959526833" MODIFIED="1255033331890" TEXT="&lt;= (show that we cannot construct a better set of generators than G)"/>
</node>
<node CREATED="1261438974063" ID="ID_1308456547" MODIFIED="1261438980317" POSITION="left" TEXT="Lemma">
<node CREATED="1261438980658" ID="ID_1690988054" MODIFIED="1261438981494" TEXT="Given">
<node CREATED="1261438981738" ID="ID_476766304" MODIFIED="1261438991079" TEXT="Sequence of independent Pauli operators"/>
<node CREATED="1261439054589" ID="ID_228734830" MODIFIED="1261439131748" TEXT="Sequence of conjugal pairs with same value for m(P_i)"/>
<node CREATED="1261440173440" ID="ID_607738992" MODIFIED="1261440187925" TEXT="g for each first in pair and sequence above intersect"/>
</node>
<node CREATED="1261439142138" ID="ID_1457939636" MODIFIED="1261439144237" TEXT="Then exists">
<node CREATED="1261439146162" ID="ID_1243043685" MODIFIED="1261439153871" TEXT="Sequence of conjugal pairs with same value for m(P_i)"/>
<node CREATED="1261440191410" ID="ID_1518402574" MODIFIED="1261440201351" TEXT="that generates the same set"/>
</node>
</node>
</node>
</map>
